[functions.orders-api]
verify_jwt = false

[functions.affiliate-discord-notification]
verify_jwt = false

[functions.stripe-analytics]
verify_jwt = false

[functions.export-all-emails]
verify_jwt = false

[functions.generate-order-pdf]
verify_jwt = false
